version: "3.8"

services:
  # 1. Database MongoDB (Đã cập nhật lên bản mới nhất)
  mongodb:
    image: mongo:5.0.15
    container_name: mongodb-CwrNguyen
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1452003
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always

  # 2. Web quản lý (Đã chuyển sang dùng Image chính chủ)
  mongo-express:
    image: mongo-express:latest
    container_name: mexpress-CwrNguyen
    environment:
      # Cấu hình kết nối admin (Sạch đẹp hơn dùng URL dài ngoằng)
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1452003
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

      # Tài khoản đăng nhập trang web (localhost:8081)
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: 1452003
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: always

volumes:
  mongodb_data_container:
